"""Command-line entry point: `python -m aidetect IMAGE [IMAGE ...]`."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from .backends import REGISTRY
from .detector import DEFAULT_MODEL_DIR, Detector
from .imageio import iter_image_files
from .metadata import read_metadata

_COLOURS = {"AI-GENERATED": "\033[31m", "AI-EDITED": "\033[35m", "REAL": "\033[32m",
            "UNCERTAIN": "\033[36m", "ERROR": "\033[33m"}
_RESET = "\033[0m"


def _collect(paths: list[str], recursive: bool) -> list[Path]:
    out: list[Path] = []
    for raw in paths:
        p = Path(raw)
        if p.is_dir():
            out.extend(iter_image_files(p, recursive=recursive))
        else:
            out.append(p)
    return out


def _bar(p: float, width: int = 20) -> str:
    if p != p:  # NaN
        return "?" * width
    filled = int(round(p * width))
    return "#" * filled + "." * (width - filled)


def build_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(
        prog="aidetect",
        description="Decide whether an image was generated by an AI model. Runs locally.")
    ap.add_argument("paths", nargs="+", help="image files or directories")
    ap.add_argument("-r", "--recursive", action="store_true",
                    help="descend into subdirectories")
    ap.add_argument("--json", action="store_true", help="emit JSON instead of a table")
    ap.add_argument("--threshold", type=float, default=None,
                    help="override the decision threshold (default: the fitted operating point)")
    ap.add_argument("--operating-point", default="fpr5",
                    choices=("fpr1", "fpr5", "fpr10", "balanced"),
                    help="how cautious to be. fpr5 (the default) is calibrated so that ~5%% of "
                         "real photos are wrongly flagged; fpr1 is stricter, balanced uses 0.5")
    ap.add_argument("--no-abstain", action="store_true",
                    help="force a real/AI answer instead of reporting UNCERTAIN in the band "
                         "where neither error rate is controlled")
    ap.add_argument("--backends", nargs="+", default=None,
                    help=f"subset of {sorted(REGISTRY)} (default: the fitted ensemble)")
    ap.add_argument("--model-dir", type=Path, default=DEFAULT_MODEL_DIR)
    ap.add_argument("--no-metadata", action="store_true",
                    help="ignore EXIF/PNG/C2PA provenance and judge on pixels alone")
    ap.add_argument("--metadata-only", action="store_true",
                    help="read provenance metadata and skip the models entirely (fast)")
    ap.add_argument("--allow-download", action="store_true",
                    help="permit fetching missing checkpoints from the Hub")
    ap.add_argument("--threads", type=int, default=None,
                    help="torch CPU threads (default: the physical core count -- using every "
                         "SMT thread measures about 2x slower)")
    ap.add_argument("--fp32", action="store_true",
                    help="disable bfloat16 autocast. Slower, and the scores drift slightly from "
                         "the ones the shipped calibration was fitted on")
    ap.add_argument("--batch-size", type=int, default=8)
    ap.add_argument("--verbose", "-v", action="store_true",
                    help="show each model's calibrated score")
    return ap


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    files = _collect(args.paths, args.recursive)
    if not files:
        print("no images found", file=sys.stderr)
        return 2

    if args.metadata_only:
        results = []
        for f in files:
            try:
                m = read_metadata(f)
                results.append({"path": str(f), "metadata_says_ai": m.says_ai,
                                "metadata_partial_ai": m.partial_ai,
                                "generator": m.generator, "evidence": m.ai_evidence,
                                "weak_evidence": list(m.weak_ai_evidence),
                                "camera_exif": m.says_camera, "has_c2pa": m.has_c2pa,
                                # A file the decoder could not open at all reads as
                                # "no AI marker", which is true and misleading. Pass
                                # the note through so it does not look analysed.
                                "error": "; ".join(m.errors) or None})
            except Exception as exc:  # noqa: BLE001
                results.append({"path": str(f), "error": f"{type(exc).__name__}: {exc}"})
        print(json.dumps(results, indent=2) if args.json else
              "\n".join(f"{r['path']}: " +
                        ("AI per metadata (" + (r.get("generator") or "?") + ")"
                         if r.get("metadata_says_ai") else
                         (r["error"] if r.get("error") else "no AI marker in metadata"))
                        for r in results))
        return 0

    try:
        detector = Detector.load(model_dir=args.model_dir, backend_names=args.backends,
                                 operating_point=args.operating_point,
                                 local_files_only=not args.allow_download,
                                 num_threads=args.threads,
                                 use_metadata=not args.no_metadata,
                                 bf16=False if args.fp32 else None)
    except Exception as exc:  # noqa: BLE001
        print(f"could not load the detector: {type(exc).__name__}: {exc}", file=sys.stderr)
        if not args.allow_download:
            print("hint: first run needs --allow-download to fetch the checkpoints",
                  file=sys.stderr)
        return 1

    if args.threshold is not None:
        detector.threshold = args.threshold
    if args.no_abstain:
        detector.low_threshold = None

    predictions = detector.predict_paths(files, batch_size=args.batch_size)

    if args.json:
        print(json.dumps([p.as_dict() for p in predictions], indent=2))
        return 0

    colour = sys.stdout.isatty()
    width = min(60, max((len(Path(p.path).name) for p in predictions), default=10))
    for pred in predictions:
        name = Path(pred.path).name
        tag = pred.verdict
        painted = f"{_COLOURS.get(tag, '')}{tag:<13}{_RESET}" if colour else f"{tag:<13}"
        score = "  n/a " if pred.p_ai != pred.p_ai else f"{pred.p_ai:6.3f}"
        print(f"{name[:width]:<{width}}  {painted} p(ai)={score}  [{_bar(pred.p_ai)}]  {pred.basis}")
        if args.verbose and pred.per_backend:
            for k, v in sorted(pred.per_backend.items()):
                print(f"{'':<{width}}    {k:<18} {v:.3f}")
    counts = {v: sum(p.verdict == v for p in predictions)
              for v in ("AI-GENERATED", "AI-EDITED", "REAL", "UNCERTAIN", "ERROR")}
    parts = [f"{counts['AI-GENERATED']} flagged AI-generated"]
    if counts["AI-EDITED"]:
        parts.append(f"{counts['AI-EDITED']} AI-edited")
    parts += [f"{counts['REAL']} real", f"{counts['UNCERTAIN']} uncertain",
              f"{counts['ERROR']} unreadable"]
    print(f"\n{len(predictions)} image(s): " + ", ".join(parts))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
